name: "Integration Test"

on: [push, pull_request]

jobs:
  integration_test:
    name: Integration Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go: ["1.15", "1.16"]
        os: [ubuntu-latest]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download ftpserver release
        uses: robinraju/release-downloader@v1.1
        with:
          repository: fclairamb/ftpserver
          tag: v0.10.0
          fileName: ftpserver-linux-amd64
      
      - name: Install
        run: sudo apt install screen
      
      - name: Create config file
        run: touch ftpserver.json
        
      - name: Prepare config file
        run: |
          cat > ftpserver.json <<- EOF
          {
            "version": 1,
            "accesses": [
              {
                "sync_and_delete": {
                  "enable": true
                },
              "user": "user",
              "pass": "password",
              "fs": "os",
              "params": {
                "basePath": "./tmp"
              }
            }
          ],
          "passive_transfer_port_range": {
            "start": 2122,
            "end": 2130
          }
          }
          EOF
          
      - name: Create test dir
        run: mkdir tmp
        
      - name: Start ftp server
        run: |
          chmod 777 ftpserver-linux-amd64
          screen -S ftpserver ./ftpserver-linux-amd64
      
      - name: Build
        run: make build

      - name: Prepare env
        run: mv Makefile.env.example Makefile.env

      - name: Integration Test
        run: make integration_test
